default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  
development:
  <<: *default
  database: <%= ENV['DEV_DATABASE_NAME'] %>
  username: <%= ENV['DEV_DATABASE_USER'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  username: <%= ENV['TEST_DATABASE_USER'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['PROD_DATABASE_NAME'] %>
  username: <%= ENV['PROD_DATABASE_USER'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>